/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router's Vite plugin.
// It will be OVERWRITTEN on every `npm run dev` or `npm run build`.
// Do not edit manually. It is also git-ignored.

import { createFileRoute, createRootRouteWithContext } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginImport } from './routes/login'
import { Route as JoinImport } from './routes/join'
import { Route as GameGameIdImport } from './routes/game/$gameId'

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as never)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as never)

const JoinRoute = JoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRoute,
} as never)

const GameGameIdRoute = GameGameIdImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRoute,
} as never)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/join' | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/join' | '/game/$gameId'
  id: '__root__' | '/' | '/login' | '/join' | '/game/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  JoinRoute: typeof JoinRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  JoinRoute,
  GameGameIdRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addRouteTypes<FileRouteTypes>()
